# -*- coding: utf-8 -*-
"""Imersão Python - Aula 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m8bbN-XQjCpyH_kDvb1bz8jSY9nOgc4y

**Aula 2 - Importação**
"""

import pandas as pd

df_principal = pd.read_excel("/content/Imersão Python - Tabela de ações - Aula 2.xlsx", sheet_name="Principal")
df_principal

df_total_acoes = pd.read_excel("/content/Imersão Python - Tabela de ações - Aula 2.xlsx", sheet_name="Total_de_acoes")
df_total_acoes

df_ticker = pd.read_excel("/content/Imersão Python - Tabela de ações - Aula 2.xlsx", sheet_name="Ticker")
df_ticker

df_chatgpt = pd.read_excel("/content/Imersão Python - Tabela de ações - Aula 2.xlsx", sheet_name="ChatGPT")
df_chatgpt